name = "love-memories"               # n’a pas besoin d’être unique
compatibility_date = "2025-05-04"    # garde la date du jour de création

# ——— Pages ———
pages_build_output_dir = "./dist"    # Vite sort ses fichiers ici

# ——— R2 binding ———
[[r2_buckets]]
binding = "BUCKET"                   # doit matcher le binding Pages UI
bucket_name = "love-memories"        # nom exact du bucket

# ——— KV binding ———
[[kv_namespaces]]
binding = "MEM_KV"                   # idem : même nom que dans Pages UI
id = "ab7a922fe39143ba87405b42d9f07ea7"   # copié depuis le tableau de bord KV
# preview_id = "yyyyy…"  # (facultatif)

[[kv_namespaces]]
binding = "PHOTOS_KV"
id        = "41552179e0a4480ea0d44aab2ea00740"

[[kv_namespaces]]
binding = "TODOS_KV"
id        = "7e801f7e338648c1998c3123ce204290"


# ——— Optionnel : routes locales pour pages dev ———
[dev]
ip = "localhost"
port = 8788
